# This file can be used to install a new conda environment specifically for this
# application, using the following commands (we choose the arbitrary name
# pyzephyr for that environment here, feel free to pick your own):
#
#   Create Environment:
#   conda env create -n pyzephyr -f conda-environment.yml
#
#   Activate Environment:
#   conda activate pyzephyr
#
#   Launch application
#   python main.py
#
channels:
- conda-forge
- defaults
dependencies:
- python
- matplotlib
- numpy
- pip
- pip:
  - -r file:requirements.txt
